// Node-only: regenerate shapes.js from the original assembler shape file
// (vendor/ro371/Sources/Diversions/Meteors/s/MetShapes, produced by GenSrc from R.Meteor2).
//   node src/apps/Meteors/genshapes.mjs
import fs from 'fs';
import path from 'path';
const here = path.dirname(new URL(import.meta.url).pathname);
const src = fs.readFileSync(path.join(here, '../../../vendor/ro371/Sources/Diversions/Meteors/s/MetShapes'), 'latin1');
const lines = src.split(/\r?\n/);
const sections = {}; let cur = null;
for (const l of lines) {
  const m = /^([A-Za-z_][A-Za-z0-9_]*)\s*$/.exec(l);
  if (m) { cur = m[1]; sections[cur] = []; continue; }
  if (cur && l.trim()) sections[cur].push(l.trim());
}
const nums = (s) => s.replace(/^DCD\s+/, '').split(',').map((x) => { x = x.trim(); return x.startsWith('&') ? parseInt(x.slice(1), 16) : parseInt(x, 10); });
const acc = sections.acctable.filter((l) => l.startsWith('DCD')).map(nums);
const routineNames = sections.Routines.filter((l) => l.startsWith('DCD')).map((l) => /DCD (\w+)/.exec(l)[1]);
// mvN: [dx, dy(up), plot]
const MV = {};
const base = [[-1, 1], [0, 1], [1, 1], [-1, 0], [0, 0], [1, 0], [-1, -1], [0, -1], [1, -1]];
base.forEach(([dx, dy], i) => { MV['mv' + (i + 1)] = [dx, dy, 0]; MV['mv' + (i + 10)] = [dx, dy, 1]; });
const routines = routineNames.map((n) => {
  if (n === 'Invisible') return [];
  let x = 0, y = 0; const pts = [];
  for (const l of sections[n]) {
    const m = /BL (mv\d+)/.exec(l);
    if (!m) continue;
    const [dx, dy, p] = MV[m[1]];
    x += dx; y += dy;
    if (p) pts.push(x, y);
  }
  return pts;
});
const sizes = sections.objectsizes.filter((l) => l.startsWith('DCD')).map(nums);
const hitNames = sections.hitshapes.filter((l) => l.startsWith('DCD')).map((l) => /DCD (\w+)/.exec(l)[1]);
const hits = hitNames.map((n) => sections[n].filter((l) => l.startsWith('DCD')).map((l) => nums(l)[0]));
const out = `// Generated by genshapes.mjs from Sources/Diversions/Meteors/s/MetShapes - do not edit.
// acc[dir]: thrust per step (16.16 pixels); plot[type]: flat [dx,dy,...] pixel offsets (y up) from the
// object position, in plotting order; sizes[type]: [x0,y0,w,h] collision box (pixels, y up);
// hit[type]: collision bitmap rows (top row first, bit 0 = leftmost pixel).
export const acc = ${JSON.stringify(acc)};
export const plot = ${JSON.stringify(routines)};
export const sizes = ${JSON.stringify(sizes)};
export const hit = ${JSON.stringify(hits)};
`;
fs.writeFileSync(path.join(here, 'shapes.js'), out);
console.log('routines', routines.length, 'sizes', sizes.length, 'hits', hits.length, 'acc', acc.length);
