// node --test tests/moreapps/index.mjs : the moreapps family's scripts
// (tools/moreapps): the disc checks, and in a real browser (after node
// tools/disc-wimplib.mjs and disc-moreapps.mjs) the 'wimplib' import
// through WimpLib$Path (jsrun-wimplib.mjs), !Boot.Resources.!WimpLib and
// $.MoreApps booted at desktop start (boot.mjs), and the !Word stub
// opening and saving .docx files (word.mjs, word-life.mjs), its caret and
// selection (word-edit.mjs), also on hostile documents
// (word-edit-hostile.mjs), and typing, deleting and undo in it
// (word-typing.mjs), also against hostile input (word-typing-
// hostile.mjs), and formatting: as drawn, by keys and the Format menu (word-format.mjs), and by its toolbar
// (word-toolbar.mjs) and its ruler (word-ruler.mjs); zoom (word-zoom.mjs); formatting against hostile input
// (word-format-hostile.mjs); list numbers and bullets drawn and edited (word-lists.mjs), also against hostile input
// (word-lists-hostile.mjs); the list buttons, keys and Format > List (word-lists-ui.mjs); untitled documents and Save / Save as
// (word-save.mjs); the Save / Discard / Cancel prompt on close, and
// Revert (word-close.mjs); New, Recent files, Quit and PreQuit
// (word-quit.mjs); documents against hostile use: saves onto open,
// locked and read-only files, 1000 Saves, input methods, shutdowns,
// Recent, 500 random actions (word-documents-hostile.mjs); Save
// boxes and existing files: Replace / Cancel (word-replace.mjs); a
// new document's whole white page (word-page.mjs); copy, cut and
// paste (word-clipboard.mjs), also against hostile input
// (word-clipboard-hostile.mjs); the RISC OS function keys and Ctrl-S /
// Ctrl-N (word-fkeys.mjs); Find and Replace (word-find.mjs); the
// WimpLib dialog builder Ui/Dialog through !Word's hook
// (word-dialog.mjs); line spacing and space before / after by keys,
// the Format menu and the toolbar (word-spacing.mjs); the Paragraph
// dialogue box (word-parabox.mjs); the Tabs dialogue box and the
// default tab stop (word-tabs.mjs); paragraph spacing against hostile
// input (word-spacing-hostile.mjs); AutoFormat lists as you type
// (word-autolist.mjs); new lists against hostile input
// (word-newlists-hostile.mjs); page and section breaks and the Insert
// menu (word-breaks.mjs), against hostile input
// (word-breaks-hostile.mjs); tab stops against hostile input
// (word-tabs-hostile.mjs); paragraph borders and shading and
// character shading as drawn (word-borders.mjs); Insert > Symbol...
// and Special character (word-symbols.mjs); Change case and Shift-F3
// (word-case.mjs); borders, symbols and change case against hostile
// input (word-borders-hostile.mjs); hyperlinks inserted, edited
// and removed, Ctrl-click to a bookmark, and bookmarks added, gone
// to and deleted (word-links.mjs); the format painter (word-painter.mjs); Word count (word-count.mjs); links,
// bookmarks, the painter and the count against hostile input (word-links-hostile.mjs); pictures drawn
// (word-pictures.mjs); pictures selected, resized and deleted
// (word-pictures-edit.mjs); Insert > Picture... (word-pictures-insert.mjs); the Picture
// dialogue box (word-picbox.mjs); pictures against hostile input (word-pictures-hostile.mjs). The unit
// tests are the *.test.mjs files
// here: node --test tests/moreapps finds them itself.
import { suite } from '../lib/suite.mjs';
suite('moreapps', [
  { name: 'disc files (Latin-1, 72 columns)', args: ['tools/disc-moreapps.mjs', '--check'], browser: false },
  { name: 'the library sources (Latin-1, 72 columns, 250 lines)', args: ['tools/disc-wimplib.mjs', '--check'], browser: false },
  { name: "the 'wimplib' import and the !Word stub", args: ['tests/moreapps/jsrun-wimplib.mjs'] },
  { name: 'WimpLib and $.MoreApps booted at start-up (cold boot)', args: ['tests/moreapps/boot.mjs'] },
  { name: '!Word opens a .docx and saves a faithful copy', args: ['tests/moreapps/word.mjs'] },
  { name: '!Word: click, drag and keys select; the caret', args: ['tests/moreapps/word-edit.mjs'] },
  { name: '!Word: hostile and odd documents (huge words, absurd sizes, random input)', args: ['tests/moreapps/word-edit-hostile.mjs'] },
  { name: '!Word: typing, deleting, undo and redo; input methods; hostile input', args: ['tests/moreapps/word-typing.mjs'] },
  { name: '!Word: typing against hostile input (storms, 50,000 paragraphs, 500 random actions)', args: ['tests/moreapps/word-typing-hostile.mjs'] },
  { name: '!Word: formatting shown (highlight, superscript, subscript, justified text); keys, pending format, the Format menu', args: ['tests/moreapps/word-format.mjs'] },
  { name: '!Word: the toolbar (style, font, size, B I U, colour, highlight, alignment); the page below it; leaks', args: ['tests/moreapps/word-toolbar.mjs'] },
  { name: '!Word: the ruler (indent markers dragged, snapping, clamping, show/hide, scroll; tab stops added, moved, removed, the selector, zoom); leaks', args: ['tests/moreapps/word-ruler.mjs'] },
  { name: '!Word: zoom (clicks, drags, caret, selection, scrolling, ruler at 50/100/200%; Ctrl+wheel; menu; 50,000 paragraphs; hiDPI); leaks', args: ['tests/moreapps/word-zoom.mjs'] },
  { name: '!Word: formatting against hostile input (50,000 paragraphs, 1000 toggles, input methods, absurd sizes, zoom while resizing, 500 random actions)', args: ['tests/moreapps/word-format-hostile.mjs'] },
  { name: '!Word: list numbers and bullets drawn in the hanging space; not selected; click on a label; 50,000 list paragraphs; 200%', args: ['tests/moreapps/word-lists.mjs'] },
  { name: '!Word: lists against hostile input (100,000 list paragraphs, Tab spam, absurd numbering, select all + Backspace, 500 random actions)', args: ['tests/moreapps/word-lists-hostile.mjs'] },
  { name: '!Word: the list buttons, Ctrl-Shift-L and Format > List (toolbar row 2 Bullets / Numbering and their galleries, pressed state, Tab / Enter / Backspace in lists, Restart / Continue / Set numbering value box, a saved list reopened, both toolbar rows at the A4 width, 30 cycles leak nothing)', args: ['tests/moreapps/word-lists-ui.mjs'] },
  { name: '!Word: untitled documents, Save, Save as and Save a copy (Save box OK and drag, typing during a save, locked / read-only / bad names, another open document, input methods)', args: ['tests/moreapps/word-save.mjs'] },
  { name: '!Word: closing asks Save / Discard / Cancel (keys, the Save box for an untitled document, one prompt); Revert; saves of a window in turn; leaks', args: ['tests/moreapps/word-close.mjs'] },
  { name: '!Word: New from the icon bar (one per double-click), Recent files (Choices:Word, missing / hostile entries), Quit and PreQuit ask once (Task Manager, shutdown, a close prompt open); 50 dirty windows; leaks', args: ['tests/moreapps/word-quit.mjs'] },
  { name: '!Word: documents against hostile use (Save as onto open / locked / read-only / bad names, 1000 Saves, Save while typing and composing, 50 dirty windows at shutdown, shutdown twice, prompts that cannot open, 10,000 hostile Recent entries, Revert of a deleted file, Quit with the Save box open, 500 random actions)', args: ['tests/moreapps/word-documents-hostile.mjs'] },
  { name: '!Word: Save boxes and existing files (a free name for a new document, Replace / Cancel, Save a copy refusing open files and holding composing text); the late commit only straight after a Save; prompts brought forward (Quit with a Save box or its Replace question, Revert); a failed Save a copy named as Save names it', args: ['tests/moreapps/word-replace.mjs'] },
  { name: '!Word: a new document shows a whole page (A4, Letter; the white page down the window, its height and end; 50% and 200%; clicks low in the page, typing, Ctrl-End, Page Down)', args: ['tests/moreapps/word-page.mjs'] },
  { name: '!Word: copy, cut and paste (real keys and the system clipboard, other programs\' HTML, the exact copy between and within documents, stale copies, Revert, files only, composing, the Edit menu, Mac Cmd keys, 50,000 paragraphs, 1000 pastes, hostile HTML, a DOMParser round trip); leaks', args: ['tests/moreapps/word-clipboard.mjs'] },
  { name: '!Word: copy, paste and Find against hostile input (50,000 paragraphs copied and Replace all, 5 MB of text, 100,000 paragraphs of HTML, 10,000-deep and script-laden HTML, files only, a table first, a real input method composing, 1000 real Ctrl-V, regular expression characters, 500 random actions)', args: ['tests/moreapps/word-clipboard-hostile.mjs'] },
  { name: '!Word: RISC OS function keys (F2 New, Ctrl-F2 Close, F3 the Save as box, Ctrl-S Save, Ctrl-N New, F8 / F9 undo and redo, Ctrl-F10 to the back; held keys once; keys not used go on; F12 the desktop\'s; menu labels; Mac Cmd-S, Cmd-N); leaks', args: ['tests/moreapps/word-fkeys.mjs'] },
  { name: '!Word: Find and Replace (Ctrl-F, F4, Ctrl-H, Ctrl-G; the one Find box: Return, Find previous, wrap, Replace, Replace all in one undo step, Match case, Whole words, link text not replaced, Escape / Close back to the document, two documents, the Edit menu, messages, 10,000 matches, a 1 MB needle, Mac Cmd-F / Cmd-G); leaks', args: ['tests/moreapps/word-find.mjs'] },
  { name: '!Word: line spacing and space before / after (Ctrl-1/2/5/0, undo, the canvas line pitch at 1.0 and 2.0, Format > Line spacing ticks, the toolbar\'s row 2 button, Mac Ctrl-1, no paragraph, 50,000 paragraphs select all + Ctrl-2 and undo under 5 s)', args: ['tests/moreapps/word-spacing.mjs'] },
  { name: 'WimpLib Ui/Dialog through !Word: every control kind by icon name, Tab / arrows between fields, typed lengths, points and numbers, a popup and a colour picked by real clicks, option and exclusive radios, Return / Escape / close icon / Cancel, mixed values, one box per key; 30 open / close cycles leak nothing', args: ['tests/moreapps/word-dialog.mjs'] },
  { name: '!Word: the Paragraph dialogue box (Format > Paragraph..., Line spacing options... in the menu and the toolbar popup; values of one paragraph, empty for a mixed selection; Before + Keep with next + OK is one undo step; Multiple 1.15, At least, Exactly, Hanging, First line; Escape, Cancel, bad text and out-of-range At; one box per document, deleted with it; 30 cycles leak nothing)', args: ['tests/moreapps/word-parabox.mjs'] },
  { name: '!Word: the Tabs dialogue box (Format > Tabs..., the Paragraph box\'s Tabs... button; the default 0.5" -> 1" moves the default tabs on screen and the ruler\'s marks, Ctrl-Z moves them back; Set / Clear / Clear all and a new default in one undo step; a stop picked from the popup; bad positions, a default of 0 and stops kept raw beep; a stale box refilled; no settings part shaded; one box per document, deleted with it; 20 cycles leak nothing)', args: ['tests/moreapps/word-tabs.mjs'] },
  { name: '!Word: paragraph spacing against hostile input (50,000 paragraphs select all + Ctrl-2 and undo, 1000 Ctrl-2 / Ctrl-1 toggles, absurd line values in files, the Paragraph box open while its window closes, 500 random actions with the spacing, flow and box ids, undo of everything)', args: ['tests/moreapps/word-spacing-hostile.mjs'] },
  { name: '!Word: AutoFormat lists as you type (real keys: * and 1. then text, Enter Enter ends, 3. continues and 7. starts anew, Tab after a., Ctrl-Z gives back the typed marker then the typing; never a space elsewhere, overwrite mode, a real input method\'s commit, paste, Replace all, undo / redo; Format > AutoFormat lists ticked, off, kept in Choices:Word with Recent across a restart, on again; Mac Cmd-Z)', args: ['tests/moreapps/word-autolist.mjs'] },
  { name: '!Word: new lists against hostile input (1000 rapid * + Ctrl-Z cycles; a space near a paragraph\'s start in 50,000 paragraphs; markers typed by script at 200 starts of 50,000 paragraphs; 100,000 paragraphs made a list; 1000 toggles; Restart spam; hostile numbering parts; lists inside styles; 500 random actions; undo of everything)', args: ['tests/moreapps/word-newlists-hostile.mjs'] },
  { name: '!Word: page breaks (a Word file\'s page and column breaks drawn as labelled rules; Ctrl-Enter mid-paragraph, at an end, in an empty paragraph, over a selection, one undo step; Left / Right one press; Backspace / Delete remove it; clicks on the rule at 100% and 200%; selection lights only its first pixels; copy and paste; saved as <w:br w:type="page"/>; section breaks; the Insert menu; page break before)', args: ['tests/moreapps/word-breaks.mjs'] },
  { name: '!Word: page and section breaks against hostile input (50,000 paragraphs select all + Ctrl-Enter / Next page / the Page break before flag and undo; 1000 Ctrl-Enter; 1000 section breaks (50 from the Insert menu); delete storms at section edges over 500 sections; select all + Backspace over 500 sections; 500 random actions; undo gives back the opened model)', args: ['tests/moreapps/word-breaks-hostile.mjs'] },
  { name: '!Word: tab stops against hostile input (10,000 stops kept raw: 64 shown, edits refused, Tabs typed; stops at +-31680 and far beyond in a file, hostile positions through the commands clamped or refused; 1000 ruler adds (64 own stops at most) and a 1000-command add / move / remove churn; Tab storms in a right-tab line; 500 random actions incl. the Tabs dialog ids and the default tab stop; undo gives back the opened model)', args: ['tests/moreapps/word-tabs-hostile.mjs'] },
  { name: '!Word: paragraph borders and shading, character shading (a box\'s four edges read from the canvas, two paragraphs in one box with the between line, shading beside the text but not in its space before, character shading under the highlight, a themed border kept raw, typing and Enter in a box, undo; 50,000 bordered paragraphs in one box: open at most 0.5 s over a nil-bordered twin, paint in view, a keystroke within 5 ms of the twin and of plain; the Borders and shading box: Box, None, sides, style, width, a typed colour, a fill, Apply to Text, one undo step each, Cancel / Escape, raw themed borders and shading beep, a stale box refilled, deleted with its document)', args: ['tests/moreapps/word-borders.mjs'] },
  { name: '!Word: Insert > Symbol... (the grid of 16 columns: sets by a popup, a real click selects and a double-click or Insert inserts with the run\'s format or a pending italic, one undo step each, the Recently used row, arrows / Return / Escape, scrolling a long set, the document last clicked in, no document: a beep and a message) and Special character (the menu; Ctrl-Shift-Space and Ctrl-Shift-- by real keys, a no-break space after "1." makes no list, a saved copy holding w:noBreakHyphen and w:softHyphen); 20 cycles leak nothing', args: ['tests/moreapps/word-symbols.mjs'] },
  { name: '!Word: Change case (Shift-F3 by a real key cycles the caret word and a selection capitals -> small -> Title Case, one undo step each, Ctrl-Z / Ctrl-Y; F3 is still Save as; Format > Change case > five modes and Next case; a bold run stays bold; a caret between spaces changes nothing)', args: ['tests/moreapps/word-case.mjs'] },
  { name: '!Word: borders, shading, symbols and change case against hostile input (50,000 bordered paragraphs in one box and one command over all of them; widths 0 and 96, spaces 0 and 31 and absurd values in a file and through the commands; theme colours kept raw and every command on them refused; 1000 Shift-F3; the Symbol window open while documents close; 500 random actions incl. the border, shading and case ids with hostile arguments, Shift-F3, Ctrl-Shift-Space, Ctrl-Shift--, the Symbol window and the menus; undo gives back the opened model)', args: ['tests/moreapps/word-borders-hostile.mjs'] },
  { name: '!Word: hyperlinks (Ctrl-K with a selection, at a caret with the text typed in the box, on a link to edit it, a javascript: address refused with a beep and a message, Escape, Remove link by a real click and Ctrl-Z, a bookmark picked from the popup and a real Ctrl-click to it, Insert > Hyperlink... and Mac Cmd-K, the box deleted with its document, Save and reopen keep the links and a copy gives <a href>, no network request; 20 cycles leak nothing) and bookmarks (Ctrl+Shift+F5, Add by Return, real Right / Left / Backspace / Delete next to the marks, the popup by location and by name, Go to, bad and 41-character names and a table refused with a beep, Delete, Insert > Bookmark..., the box deleted with its document, 20 cycles leak nothing)', args: ['tests/moreapps/word-links.mjs'] },
  { name: '!Word: the format painter (the toolbar\'s row 2 button: Select once, Adjust sticky until Escape or another click on the button; the caret picks the character and paragraph format, a selection inside a paragraph its first character only; a click paints the word, a drag the selection; a list format carried or taken away; one undo step; no change no step; Escape does nothing else; Format > Format painter ticked; no listener leak)', args: ['tests/moreapps/word-painter.mjs'] },
  { name: '!Word: Edit > Word count... (the whole document with a table\'s text, a link\'s text and a field\'s result in and field codes, deleted text and empty paragraphs out; a selection across two paragraphs; refreshed when asked again; Close by a real click, Escape and Return; nothing changed in the document; the box deleted with it; 20 cycles leak nothing)', args: ['tests/moreapps/word-count.mjs'] },
  { name: '!Word: hyperlinks, bookmarks, the format painter and the word count against hostile input (bad addresses in the Hyperlink box refused or made safe; a 1 MB address typed and in a file; 10,000 bookmarks listed, added, moved, gone to and deleted; duplicate names and clashing ids in a file; 1000 painter uses by real clicks; the word count of 1,000,000 words; 500 random actions incl. the boxes filled with hostile text; undo gives back the opened model; no network request)', args: ['tests/moreapps/word-links-hostile.mjs'] },
  { name: '!Word: pictures drawn (a PNG, a JPEG and a GIF from their bitmaps, a floating picture dashed, EMF and missing parts as labelled boxes; only pictures in view decoded, each once; 1000 pictures open under 2 s; 200%; a window closed while decoding)', args: ['tests/moreapps/word-pictures.mjs'] },
  { name: '!Word: pictures selected, resized and deleted (a real click selects, eight black handles; Shift-Right; Delete / Backspace and undo; the SE handle keeps the proportions, the e handle the height, Shift frees a corner; Escape during a drag; a floating picture beeps; Ctrl-Z selects the picture; 50% and 200%; a double-click calls onPicture; 30 cycles leak nothing)', args: ['tests/moreapps/word-pictures-edit.mjs'] },
  { name: '!Word: Insert > Picture... (a typed path and Return puts the picture in at the caret in one undo step; a missing path, a directory, an address, a text file and a 21 MB file refused with a message; a dropped file icon fills the path; an edit during a slow read puts nothing in; the box goes with its document; 20 cycles leak nothing; saved and reopened, drawn)', args: ['tests/moreapps/word-pictures-insert.mjs'] },
  { name: '!Word: the Picture dialogue box (a double-click and Format > Picture... open it filled; shaded without a picture; Escape and Cancel; Width 3 + OK one undo step; an out of range size keeps the box; alt text saved; a floating picture size shaded and its anchor XML kept; Reset size on a 300 dpi PNG; a stale selection refills it; 20 cycles leak nothing)', args: ['tests/moreapps/word-picbox.mjs'] },
  { name: '!Word: pictures against hostile input (100 pictures in one paragraph; 1000 pictures in 1000 paragraphs scrolled end to end, decodes never more than seen, the cache under 128 MB; a 50 MB part and IHDR, SOF and GIF-frame bombs as labelled boxes with no decode; a corrupt PNG decoded once, never retried; 1000 real resize drags; select all of 50,000 paragraphs with 100 pictures, Delete and undo under 5 s; a copy between documents; 500 random actions incl. the dialogs with hostile text and dropped and pasted files; undo gives back the opened model; no request)', args: ['tests/moreapps/word-pictures-hostile.mjs'] },
  { name: '!Word without its fonts; open, close and Quit leave nothing behind', args: ['tests/moreapps/word-life.mjs'] },
]);
