// Application registry: one line per application. Each entry is the path (relative to
// src/apps/) of a module whose default export is an application descriptor (see
// docs/CORE_API.md). Add your app here - keep the list sorted.
export default [
  './_Example/app.js',
  './Alarm/app.js',
  './ARPlayer/app.js',
  './Blocks/app.js',
  './Bookworm/app.js',
  './ChangeFSI/app.js',
  './Chars/app.js',
  './Clock/app.js',
  './CloseUp/app.js',
  './Configure/app.js',
  './Draw/app.js',
  './Edit/app.js',
  './Flasher/app.js',
  './Flasher/helpapp.js',
  './Help/app.js',
  './Maestro/app.js',
  './MemNow/app.js',
  './Meteors/app.js',
  './MineHunt/app.js',
  './Paint/app.js',
  './Patience/app.js',
  './PhotoView/app.js',
  './Player/app.js',
  './Printers/app.js',
  './Puzzle/app.js',
  './SciCalc/app.js',
  './SlideShow/app.js',
  './Squash/app.js',
  './SysRes/fonts.js',
  './SysRes/scrap.js',
  './SysRes/system.js',
];
