// BASIC V error numbers and messages (vendor/ro371/Sources/Programmer/BASIC/ErrorMsgs and
// Resources/UK/Messages). Each entry: key -> [ERR number, message].

export const ERRORS = {
  EREXCEPT: [0, 'Unknown setting of exception control.'],
  ERSILL: [0, 'Silly!'],
  ERNUMM: [0, 'No room to do this renumber'],
  ERNUMO: [0, 'Line numbers larger than 65279 would be generated by this renumber'],
  ALLOCR: [0, 'No room'],
  ERLINELONG: [0, 'Line too long'],
  ERSTOP: [0, 'Stopped'],
  ERLISTO: [0, 'Invalid LISTO option'],
  ERTWINO: [0, 'Invalid TWINO option'],
  ERRQ1: [0, 'Corruption of stack'],
  ONERRX: [0, 'Error control status not found on stack for RESTORE ERROR'],
  BADIC: [0, 'Missing incore name'],
  USESLINENUMBERS: [0, 'LIST/TWIN found line number reference'],
  HELPTOKENNO: [0, 'HELP has no information on this keyword'],
  BADIPHEX: [0, 'Incorrect in-core file description'],
  INSTALLBAD: [0, 'INSTALL cannot be used in a program'],
  ERASS1: [1, 'No such mnemonic'],
  ERASS1EQU: [1, 'No such suffix on EQU'],
  ERASS2: [2, 'Bad immediate constant'],
  ERASS2A: [2, 'Bad address offset'],
  ERASS2LIM: [2, 'Assembler limit reached'],
  ERASS2S: [2, 'Bad shift'],
  ERASS3: [3, 'Bad register'],
  ERASSMUL: [3, 'Duplicate register in multiply'],
  MISSEQ: [4, 'Missing ='],
  MISSEQFOR: [4, 'Missing = in FOR statement'],
  MISTAK: [4, 'Mistake'],
  ERCOMM: [5, 'Missing ,'],
  ERTYPEINT: [6, 'Type mismatch: number needed'],
  ERTYPENUM: [6, 'Type mismatch: numeric variable needed'],
  ERTYPENUMARRAY: [6, 'Type mismatch: numeric array needed'],
  ERTYPESTR: [6, 'Type mismatch: string needed'],
  ERTYPESTRING: [6, 'Type mismatch: string variable needed'],
  ERTYPESTRINGARRAY: [6, 'Type mismatch: string array needed'],
  ERTYPEARRAY: [6, 'Type mismatch: array needed'],
  ERTYPEARRAYB: [6, 'Type mismatch between arrays'],
  ERTYPEARRAYC: [6, "Can't assign to array of this size"],
  ERSIZE: [6, 'Array type mismatch as parameter'],
  ERTYPESWAP: [6, "Can't SWAP arrays of different types"],
  ERRFN: [7, 'Not in a function'],
  ERDOLL: [8, 'Too low a value for $<number>'],
  ERMISQ: [9, 'Missing "'],
  ERDIMFN: [10, 'DIM() function needs an array'],
  ERMATMULSPACE: [10, 'No room to do matrix multiply with source(s) the same as destination'],
  BADDIMSUB: [10, 'Impossible dimension'],
  BADDIMLIST: [10, 'No end of dimension list )'],
  BADDIM: [10, 'Bad DIM statement'],
  BADDIMSIGN: [10, "Can't DIM negative amount"],
  ERNDIM: [10, 'Arrays cannot be redimensioned'],
  BADDIMSIZE: [11, 'No room for this DIM'],
  DIMRAM: [11, 'No room for this dimension'],
  ERREND: [11, 'Attempt to allocate insufficient memory'],
  ERRENDARRAYREF: [11, 'Unreferenced local array in END='],
  CANTLOAD: [11, 'No room for program'],
  ERRNLC: [12, 'Items can only be made local in a function or procedure'],
  ENDPRE: [13, 'Not in a procedure'],
  ERARRW: [14, 'Reference array incorrect'],
  ERARRY: [14, 'Unknown array'],
  ERARRYDIM: [14, 'Unknown array in DIM() function'],
  ERARRZ: [14, 'Undimensioned array'],
  ERRSUB: [15, 'Subscript out of range'],
  ERRSB2: [15, 'Incorrect number of subscripts'],
  ERSYNT: [16, 'Syntax error'],
  ESCAPE: [17, 'Escape'],
  ZDIVOR: [18, 'Division by zero'],
  ERLONG: [19, 'String too long'],
  FOVR: [20, 'Number too big'],
  FOVR1: [20, 'Number too big for arc Sine or arc Cosine'],
  FSQRTN: [21, 'Negative root'],
  ERFLOG: [22, 'Logarithm range'],
  FRNGQQ: [23, 'Accuracy lost in Sine/Cosine/Tangent'],
  ERFEXP: [24, 'Exponent range'],
  FACERR: [26, 'Unknown or missing variable'],
  ERVARAR: [26, "Can't use array reference here"],
  ERBRA: [27, 'Missing )'],
  ERBRA1: [27, 'Missing ('],
  ERASSB1: [27, 'Missing ]'],
  ERASSB2: [27, 'Missing {'],
  ERASSB3: [27, 'Missing }'],
  ERHEX: [28, 'Bad Hex'],
  ERHEX2: [28, 'Hex number too large'],
  ERBIN: [28, 'Bad Binary'],
  FNMISS: [29, 'No such function/procedure'],
  FNCALL: [30, 'Bad call of function/procedure'],
  ARGMAT: [31, 'Arguments of function/procedure incorrect'],
  ARGMATRET: [31, 'Invalid RETURN actual parameter'],
  ARGMATARR: [31, 'Invalid array actual parameter'],
  ERNEXT: [32, 'Not in a FOR loop'],
  NEXTER: [33, "Can't match FOR"],
  FORCV: [34, 'Bad FOR control variable'],
  FORSTEP: [35, 'The step cannot be zero'],
  FORTO: [36, 'Missing TO'],
  ERDEEPPROC: [37, 'No room for function/procedure call'],
  ERGOSB: [38, 'Not in a subroutine'],
  ONER: [39, 'ON syntax'],
  ONRGER: [40, 'ON range'],
  NOLINE: [41, 'No such line'],
  DATAOT: [42, 'Out of data'],
  ERRDATASTACK: [42, 'DATA pointer not found on stack for RESTORE DATA'],
  ERREPT: [43, 'Not in a REPEAT loop'],
  ERDEEPNEST: [44, 'Too many nested structures'],
  CHANNE: [45, 'Missing #'],
  ERWHIL: [46, 'Not in a WHILE loop'],
  NOENDC: [47, 'Missing ENDCASE'],
  ERCASE1: [48, 'OF missing from CASE statement'],
  ERCASE: [48, 'CASE..OF statement must be the last thing on a line'],
  NOENDI: [49, 'Missing ENDIF'],
  ERMOUS: [50, 'Bad MOUSE variable'],
  ERSYSINPUTS: [51, 'Too many input expressions for SYS'],
  ERSYSOUTPUTS: [51, 'Too many output variables for SYS'],
  ERINSTALL: [52, "Can't install library"],
  BADPRO1: [52, 'Bad program used as function/procedure library'],
  NOLIBROOM: [52, 'No room for library'],
};

/** An error raised by BASIC or by the "operating system" (SWIs, filing system...). */
export class BasicError extends Error {
  constructor(number, message, key = null) {
    super(message);
    this.number = number;   // ERR
    this.key = key;         // e.g. 'MISTAK'
  }
}

/** Throw/construct a BASIC error by its source-code key, e.g. err('MISTAK'). */
export function err(key) {
  const e = ERRORS[key];
  if (!e) return new BasicError(0, key, key);
  return new BasicError(e[0], e[1], key);
}

/** Make an OS-style error (e.g. from a SWI or file system) */
export function osError(number, message) {
  return new BasicError(number >>> 0 === number ? number : number | 0, message);
}

// Common OS error numbers used by the emulated OS layer
export const OSERR = {
  FILE_NOT_FOUND: [0xD6, 'File \'%s\' not found'],
  NOT_FOUND: [0xD6, 'Not found'],
  CHANNEL: [0xDE, 'Channel'],
  EOF: [0xDF, 'End of file'],
  BAD_COMMAND: [0xFE, 'Bad command'],
  BAD_SWI: [0x1E6, 'SWI name not known'],
  NO_SWI: [0x1E6, 'SWI &%s not known'],
  BAD_MODE: [0x19, 'Bad MODE'],
  LOCKED: [0xC3, 'Locked'],
  ESCAPE: [17, 'Escape'],
};
