// HELP texts from vendor/ro371/Sources/OS_Core/Internat/Messages/UK/Resources/BASIC/Messages
// (dictionary tokens expanded; \r = line break for OS_PrettyPrint).
export const HELP = {
 "HELPTOKENNO": "HELP has no information on this keyword",
 "HAND": "Bitwise logical AND between two integers. Priority 6.",
 "HABS": "This function gives the magnitude (absolute value) of a number (<factor>).",
 "HACS": "This function gives the arc cosine of a number (<factor>).",
 "HADVAL": "This function gives the value of the specified analogue port or buffer.",
 "HASC": "This function gives the ASCII code of the first character of a string.",
 "HASN": "This function gives the arc sine of a number (<factor>).",
 "HATN": "This function gives the arc tangent of a number (<factor>).",
 "HAUTO": "This command generates line numbers for typing in a program.\rAUTO [<base number>[,<step size>]]",
 "HAPPEND": "This command appends a file to the program and renumbers the new lines.",
 "HBGET": "This function gives the next byte from the specified file: BGET#<channel>.",
 "HBPUT": "BPUT#<channel>,<number>: put byte to open file.\rBPUT#<channel>,<string>[;]: put string to open file, with[out] newline.",
 "HBEATS": "BEATS <expression>: set the number of microbeats in a bar.\rAs a function BEATS gives the current number of microbeats.",
 "HBEAT": "This function gives the current microbeat number.",
 "HCOLOUR": "COLOUR a [TINT t]: set text foreground colour [and tint] (background 128+a).\rCOLOUR a,p: set palette entry for logical colour a to physical colour p.\rCOLOUR r,g,b: set colour to r, g, b.\rCOLOUR a,r,g,b: set palette entry for a to r, g, b physical colour.",
 "HCONST": "Introduces a line number reference in internal form.",
 "HCALL": "CALL<expression>[,<variable>]^: Call machine code.",
 "HCASE": "CASE <expression> OF: start of CASE..WHEN..OTHERWISE..ENDCASE structure.",
 "HCHAIN": "Load and run a new Basic program.",
 "HCHR$": "This function gives the one character string of the supplied ASCII code.",
 "HCLEAR": "Forget all variables.",
 "HCLOSE": "CLOSE#<channel>: close specified file.",
 "HCLG": "Clear graphics screen.",
 "HCLS": "Clear text screen.",
 "HCOS": "This function gives the cosine of a number (<factor>).",
 "HCOUNT": "This function gives the number of characters PRINTed since the last newline.",
 "HCIRCLE": "CIRCLE [FILL] x,y,r: draw circle outline [solid].",
 "HCRUNCH": "This command removes specified spaces from the current program.\rCRUNCH <expression>. The bits in the number mean:\r0: spaces before statements\r1: spaces in statements\r2: REM statements (except first)\r3: empty statements\r4: empty lines",
 "HDATA": "Introduces line of DATA to be READ. The list of items is separated by commas.\rLOCAL DATA, RESTORE DATA: save and restore current DATA pointer.",
 "HDEG": "This function gives the value in degrees of a number in radians.",
 "HDEF": "Define function or procedure: DEF FN|PROC<name>[(<parameter list>)].\rEnd function with =<expression>; end procedure with ENDPROC.",
 "HDELETE": "This command deletes all lines between the specified numbers.\rDELETE <start line number>,<end line number>",
 "HDIV": "Integer division, rounded towards zero, between two integers. Priority 3.",
 "HDIM": "DIM fred(100,100): create and initialise an array.\rDIM fred% 100: allocate space for a byte array etc.\rDIM(fred()): function gives the number of dimensions.\rDIM(fred(),n): function gives the size of the n'th dimension.",
 "HDRAW": "DRAW [BY] x,y: graphics draw to [relative by] x,y.",
 "HENDPROC": "End of procedure definition.",
 "HEDIT": "This command calls the ARM BASIC Editor.",
 "HENDWHILE": "End of WHILE structure. See WHILE.",
 "HENDCASE": "End of CASE structure at start of line. See CASE.",
 "HENDIF": "End of block IF structure at start of line. See IF.",
 "HEND": "END: statement marking end of program execution.\rEND=<expression>: alter amount of memory allocated to BASIC.\rAs a function END gives the end address of memory used.",
 "HENVELOPE": "ENVELOPE takes 14 numeric parameters separated by commas.",
 "HELSE": "Part of the IF..THEN..ELSE structure. If found at the start of line, it is part of the block IF..THEN..ELSE..ENDIF structure.\rELSE can also appear in ON .. GOTO|GOSUB|PROC to set the default option.",
 "HEVAL": "This function evaluates a string: EVAL(\"2*X+1\").",
 "HERL": "This function gives the line number of the last error.",
 "HERROR": "Part of ON ERROR; LOCAL ERROR and RESTORE ERROR statements.\rCause an error: ERROR [EXT] <number>,<string>.",
 "HEOF": "This function gives TRUE if at end of open file; else FALSE: EOF#<channel>.",
 "HEOR": "Bitwise logical Exclusive-OR between two integers. Priority 7.",
 "HERR": "This function gives the error number of the last error.",
 "HEXP": "This function gives the exponential of a number (<factor>).",
 "HEXT": "This function gives the length (extent) of an open file: EXT#<channel>.\rEXT#<channel>=<expression> sets the length of an open file.",
 "HELLIPSE": "ELLIPSE [FILL] x,y,maj,min[,angle]: draw ellipse outline [solid].",
 "HFOR": "FOR <variable> = <start value> TO <limit value> [STEP <step size>].",
 "HFALSE": "This function gives the logical value 'false' i.e. 0.",
 "HFILL": "FILL [BY] x,y: flood fill from [relative to] point x,y.",
 "HFN": "Call a function with FNfred(x,y): define one with DEF FNfred(a,b).",
 "HGOTO": "GOTO <line number>: go to line number.",
 "HGET$": "This function gives the next input character as a one character string.\rGET$#<channel> gives next string from the file.",
 "HGET": "This function gives the ASCII value of the next character in the input stream.",
 "HGOSUB": "GOSUB <line number>: call subroutine at line number.",
 "HGCOL": "GCOL a [TINT t]: set graphics foreground colour [and tint] (background 128+a).\rGCOL <action>,a [TINT t]: set graphics fore|background colour and action.\rGCOL [<action>,]r,g,b: set colour to r, g, b.",
 "HHIMEM": "This pseudo-variable reads or sets the address of the end of BASIC's memory.",
 "HHELP": "This command gives help on usage of the interpreter.",
 "HINPUT": "INPUT [LINE]['|TAB|SPC][\"display string\"][,|;]<variable>: input from user.\rINPUT#<channel>,<list of variables>: input data from open file.",
 "HIF": "Single line if: IF <expression> [THEN] <statements> [ELSE <statements>].\rBlock if: IF <expression> THEN<newline>\r            <lines>\roptional: ELSE <lines>\rmust:     ENDIF",
 "HINKEY$": "CHR$(INKEY...): see INKEY.",
 "HINKEY": "INKEY 0 to 32767: function waits <number> centiseconds to read character.\rINKEY -255 to -1: function checks specific key for TRUE|FALSE.\rINKEY -256: function gives operating system number.",
 "HINT": "This function gives the nearest integer less than or equal to the number.",
 "HINSTR": "INSTR(<string>,<sub string>[,<start position>]) find sub string position.",
 "HINSTALL": "This command permanently installs a library: see HELP LIBRARY.",
 "HLIST": "This command lists the program:\rLIST [<line number>][,[<line number>]][IF<pattern>]. list section [if pattern]\rLISTO <option number>. Bits mean:-\r0: space before line\r1: indent structure\r2: split lines at :\r3: don't list line number\r4: list tokens in lower case",
 "HLINE": "Draw a line: LINE x1,y1,x2,y2\rPart of INPUT LINE or LINE INPUT statement.",
 "HLOAD": "This command loads a new program.",
 "HLOMEM": "This pseudo-variable reads or sets the address of the start of the variables.",
 "HLOCAL": "LOCAL <list of variables>: make things private to function or procedure.\rLOCAL DATA: save DATA pointer on stack.\rLOCAL ERROR: save error control status on stack.",
 "HLEFT$": "LEFT$(<string>,<number>): gives leftmost number of characters from string.\rLEFT$(<string>): gives leftmost LEN-1 characters.\rLEFT$(<string variable>[,<count>])=<string>: overwrite characters from start.",
 "HLEN": "This function gives the length of a string.",
 "HLET": "Optional part of assignment.",
 "HLOG": "This function gives the common logarithm (base 10) of a number (<factor>).",
 "HLN": "This function gives the natural logarithm (base e) of a number (<factor>).",
 "HLIBRARY": "LIBRARY <string>: functions and procedures of the named program can be used.",
 "HLVAR": "This command lists all variables in use.",
 "HMID$": "MID$(<string>,<position>): gives all of string starting from position.\rMID$(<string>,<position>,<count>): gives some of string from position.\rMID$(<string variable>,<position>[,<count>])=<string>: overwrite characters.",
 "HMODE": "MODE <number>|<string>: set screen mode.\rAs a function MODE gives the current screen mode.",
 "HMOD": "Remainder after integer division between two integers. Priority 3.\rThe MOD function gives the square root of the sum of the squares of all the elements in a numeric array.",
 "HMOVE": "MOVE [BY] x,y: graphics move to [relative by] x,y.",
 "HMOUSE": "MOUSE x,y,z[,t]: sets x,y to mouse position; z to button state [t to time].\rMOUSE COLOUR a,r,g,b: set mouse palette entry for a to r, g, b physical colour.\rMOUSE OFF: turn mouse pointer off.\rMOUSE ON [a]: sets mouse pointer 1 [or a].\rMOUSE RECTANGLE x,y,width,height: constrain mouse movement to inside rectangle.\rMOUSE STEP a[,b]: sets mouse step multiplier to a,a [or a,b].\rMOUSE TO x,y: positions mouse and pointer at x,y.",
 "HNEXT": "NEXT [<variable>[,<variable>]^]: closes one or several FOR..NEXT structures.",
 "HNEW": "This command erases the current program.",
 "HNOT": "This function gives the number with all bits inverted (0 and 1 exchanged).",
 "HOLD": "This command recovers the program just after a NEW.",
 "HON": "ON: cursor on.\rON ERROR [LOCAL|OFF]: define error handler.\rON <expression> GOTO|GOSUB|PROC.... ELSE: call from specified list item.",
 "HOFF": "OFF: turn cursor off.\rPart of TRACE OFF, ON ERROR OFF statements.",
 "HOF": "Part of the CASE <expression> OF statement.",
 "HORIGIN": "ORIGIN x,y: sets x,y as the new graphics 0,0 point.",
 "HOR": "Bitwise logical OR between two integers. Priority 7.",
 "HOPENIN": "Open for Input: the function opens a file for input.",
 "HOPENOUT": "Open for Output: the function opens a file for output.",
 "HOPENUP": "Open for Update: the function opens a file for input and output.",
 "HOSCLI": "OSCLI <string>: give string to Operating System Command Line Interpreter.",
 "HOTHERWISE": "Identifies case exceptional section at start of line. See CASE.",
 "HOVERLAY": "OVERLAY <string array>: set an array of filenames for overlay libraries.",
 "HPRINT": "PRINT ['|TAB|SPC][\"display string\"][<expression>][;] print items in fields defined by @% - see HELP @%\rPRINT#<channel>,<list of expressions>: print data to open file.",
 "HPAGE": "This pseudo-variable reads or sets the address of the start of the program.",
 "HPTR": "This function gives the position in a file: PTR#<channel>.\rPTR#<channel>=<expression> sets the position in a file.",
 "HPI": "This function gives the value of 'pi' 3.1415926535.",
 "HPLOT": "PLOT n,x,y: graphics operation n.",
 "HPOINT": "POINT [BY] x,y: set pixel at [relative to] x,y.\rPOINT TO x,y: position pointer at x,y if not linked to mouse.",
 "HPOINTPAR": "POINT(x,y) gives the logical colour of a graphics point.",
 "HPROC": "Call a procedure with PROCfred(x,y); define one with DEF PROCfred(a,b).",
 "HPOS": "This function gives the x-coordinate of the text cursor.",
 "HQUIT": "QUIT: leave the interpreter.\rAs a function QUIT gives TRUE if BASIC was entered with a -quit option.",
 "HRETURN": "End of subroutine.",
 "HREPEAT": "REPEAT: start of REPEAT..UNTIL structure; statement delimiter not required.",
 "HREPORT": "REPORT: print last error message.\rREPORT$ function gives string of last error string.",
 "HREAD": "READ <list of variables>: read the variables in turn from DATA statements.",
 "HREM": "Ignores rest of line.",
 "HRUN": "Clear variables and start execution at beginning of program.",
 "HRAD": "This function gives the value in radians of a number in degrees.",
 "HRESTORE": "RESTORE [+][<number>]: restore the data pointer to first or given line, or move forward <number> lines from the start of the next line.\rRESTORE DATA: restore DATA pointer from stack.\rRESTORE ERROR: restore error control status from stack.",
 "HRIGHT$": "RIGHT$(<string>,<number>): gives rightmost number of characters from string.\rRIGHT$(<string>): gives rightmost character.\rRIGHT$(<string variable>[,<count>])=<string>: overwrite characters at end.",
 "HRND": "RND: function gives a random integer.\rRND(n) where n<0: initialise random number generator based on n.\rRND(0): last RND(1) value.\rRND(1): random real 0..1.\rRND(n) where n>1: random value between 1 and INT(n).",
 "HRECTANGLE": "RECTANGLE [FILL] xlo,ylo,width[,height] [TO xlo,ylo]:\rDraw a rectangle outline [solid] or copy [move] the rectangle.",
 "HRENUMBER": "This command renumbers the lines in the program:\rRENUMBER [<base number>[,<step size>]]",
 "HSTEP": "Part of the FOR..TO..STEP structure.",
 "HSAVE": "This command saves the current program.",
 "HSGN": "This function gives the values -1, 0, 1 for negative, zero, positive numbers.",
 "HSIN": "This function gives the sine of a number (<factor>).",
 "HSQR": "This function gives the square root of a number (<factor>).",
 "HSOUND": "SOUND <channel>,<amplitude>,<pitch>,<duration>[,<start beat>]: make a sound.\rSOUND ON|OFF: enable|disable sounds.",
 "HSPC": "In PRINT or INPUT statements, prints out n spaces: PRINT SPC(10).",
 "HSTR$": "STR$[~]<number>: gives string representation [in hex] of a number (<factor>).",
 "HSTRING$": "STRING$(<number>,<string>): gives string replicated the number of times.",
 "HSTOP": "Stop program.",
 "HSTEREO": "STEREO <channel>,<position>: set the stereo position for a channel.",
 "HSUM": "This function gives the sum of all elements in an array.\rSUMLEN gives the total length of all elements of a string array.",
 "HSWAP": "SWAP <variable>,<variable>: exchange the contents.",
 "HSYS": "The SYS statement calls the operating system:\rSYS <expression> [,<expression>]^ [TO <variable>[,<variable>]^[;<variable>]]",
 "HTAN": "This function gives the tangent of a number (<factor>).",
 "HTAB": "In PRINT or INPUT statements:\rTAB to column n: PRINT TAB(10)s$.\rTAB to screen position x,y: PRINT TAB(10,20)s$.",
 "HTEMPO": "TEMPO <expression>: set the sound microbeat tempo.\rAs a function TEMPO gives the current microbeat tempo.",
 "HTEXTLOAD": "This command loads a new program, converting from text form if required.",
 "HTEXTSAVE": "This command saves the current program as text [with a LISTO option].\rTEXTSAVE[O <expression>,] <string>",
 "HTHEN": "Part of the IF..THEN structure. If THEN is followed by a newline it introduces a block structured IF..THEN..ELSE..ENDIF.",
 "HTIME": "This pseudo-variable reads or sets the computational real time clock. TIME$ reads or sets the display version of the clock.",
 "HTINT": "TINT a,t: set the tint for COLOUR|GCOL|fore|back a to t in 256 colour modes.\rAlso available as a suffix to GCOL and COLOUR.\rAs a function TINT(x,y) gives the tint of a point in 256 colour modes.",
 "HTO": "TO: part of FOR..TO..\rTOP: gives the address of the end of the program.",
 "HTRACE": "TRACE [STEP] ON|OFF|PROC|<number>: trace [in single step mode] on or off or procedure or function calls or lines below the number.\rTRACE TO <string>: send all output to stream <string>\rTRACE CLOSE: close stream output. Expression: TRACE gives handle of the stream.",
 "HTRUE": "This function gives the logical value 'true' i.e. -1.",
 "HTWINO": "This command converts the program to text with a LIST option and calls Twin.",
 "HTWIN": "This command converts the program to text and calls Twin.",
 "HUNTIL": "UNTIL <expression>: end of REPEAT..UNTIL structure.",
 "HUSR": "This function gives the value returned by a machine code routine.",
 "HVDU": "VDU <number>[;|][,<number>[;|]]: list of values to be sent to vdu.\r, only - 8 bits.\r; 16 bits.\r| 8 bytes of zeroes.",
 "HVAL": "This function gives the numeric value of a textual string e.g. VAL\"23\".",
 "HVPOS": "This function gives the y-coordinate of the text cursor.",
 "HVOICES": "VOICES <expression>: set the number of sound voice channels.",
 "HVOICE": "VOICE <channel>,<string>: assign a named sound algorithm to the voice channel.",
 "HWHILE": "WHILE <expression>: start of WHILE..ENDWHILE structure.",
 "HWHEN": "WHEN <expression>[,<expression>]^: identifies case section at start of line.\rSee CASE.",
 "HWAIT": "Wait for vertical sync.",
 "HWIDTH": "WIDTH <expression>: set width of output.",
 "HASM": "Assembly language is contained in [] and assembled at P%. Labels follow '.'.\rSyntax:\rSWI[<cond>] <expr>\rADC|ADD|AND|BIC|EOR|ORR|RSB|RSC|SBC|SUB[<cond>][S] <reg>,<reg>,<shift>\rMOV|MVN[<cond>][S] <reg>,<shift>\rCMN|CMP|TEQ|TST[<cond>][S|P] <reg>,<shift>\rMLA[<cond>][S] <reg>,<reg>,<reg>,<reg>\rMUL[<cond>][S] <reg>,<reg>,<reg>\rLDR|STR[<cond>][B] <reg>, '[ <reg>[,<shift>] '] [,<shift>][!]\rLDM|STM[<cond>]DA|DB|EA|ED|FA|FD|IA|IB <reg>[!],{<reg list>}[^]\rB[L][<cond>] <label>\rOPT|=|DCB|EQUB|DCW|EQUW|DCD|EQUD|EQUS <expr>\rADR[<cond>] <reg>,<label>\rALIGN\rwhere <shift>=<reg>|#<expr>|<reg>,ASL|LSL|LSR|ASR|ROR <reg>|#<expr>|RRX\rand <cond>=AL|CC|CS|EQ|GE|GT|HI|HS|LE|LS|LT|LO|MI|NE|NV|PL|VC|VS\rand <reg>=R0 to 15 or PC or <expr>\r",
 "H0": "Help can do: 'HELP .' or 'HELP A' to print the names of keywords;\r'HELP PRINT' for help on any particular keyword and 'HELP [' for assembler.\r\r",
 "H1": "Possible keywords:\r",
 "H@": "This pseudo-variable reads or sets the number print format:\rPRINT @% gives a number, but LVAR and @%= use strings\r\"G<number>.<number>\" general format field and number of digits\r\"E<number>.<number>\" exponent format field and number of digits\r\"F<number>.<number>\" fixed format field and number of digits after '.'\rAll parts optional. , or . in the above prints , or . as the decimal point.\rLeading + means @% applies to STR$ also.\r",
 "HBASBAS": "BASIC is the ARM BBC BASIC interpreter.\u0000"
};
